import { randomBytes } from "node:crypto";
import { mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import webPush from "web-push";
import { DEFAULT_VAPID_SUBJECT, type WebPushConfig } from "./config.js";

/**
 * The gateway's own VAPID keypair, minted and persisted the first time.
 *
 * Push was complete in every other respect and off for everyone, because the
 * only way to supply keys was three environment variables and nothing in the
 * project generated them. An operator had to know what VAPID is, find a tool to
 * produce a P-256 keypair in the right encoding, and pin the private half in a
 * shell profile — where any `ps` can read it. So notifications were a feature
 * that shipped switched off with no switch.
 *
 * This is the same bargain `pairing-token.ts` already makes, for the same
 * reasons: a file the gateway owns at mode 0600, created on demand, is both
 * easier and safer than an environment variable. Explicit
 * `PRIME_WEB_VAPID_*` keys still win — an operator who has already made a pair,
 * or who wants the same identity across two installs, keeps that.
 *
 * Losing the file is not data loss so much as an identity change: existing
 * subscriptions are bound to the key that created them and stop being
 * decryptable, so each device re-subscribes the next time it enables
 * notifications. `enablePush` in the web client already unsubscribes and
 * re-subscribes for exactly this case.
 */

/** A P-256 public point is 65 bytes uncompressed; the private scalar is 32. */
const PUBLIC_KEY_BYTES = 65;
const PRIVATE_KEY_BYTES = 32;
const UNCOMPRESSED_POINT_TAG = 0x04;
const MAX_KEY_FILE_BYTES = 4 * 1024;

interface StoredKeys {
  publicKey: string;
  privateKey: string;
}

function isBase64UrlOfLength(value: unknown, bytes: number): value is string {
  return typeof value === "string"
    && /^[A-Za-z0-9_-]+$/u.test(value)
    && Buffer.from(value, "base64url").byteLength === bytes;
}

function isStoredKeys(value: unknown): value is StoredKeys {
  if (value == null || typeof value !== "object") return false;
  const keys = value as Record<string, unknown>;
  return isBase64UrlOfLength(keys.publicKey, PUBLIC_KEY_BYTES)
    && isBase64UrlOfLength(keys.privateKey, PRIVATE_KEY_BYTES);
}

/**
 * Generated by the same library that later signs with them, rather than by hand
 * from `node:crypto`: the encoding a push service will accept is `web-push`'s
 * business, and two implementations of it are one more than is needed. The
 * lengths are still checked, because a key that is wrong here fails at send
 * time, on a phone, with nothing on screen to say so.
 */
export function generateVapidKeys(): StoredKeys {
  const { publicKey, privateKey } = webPush.generateVAPIDKeys();
  const publicBytes = Buffer.from(publicKey, "base64url");
  if (publicBytes.byteLength !== PUBLIC_KEY_BYTES || publicBytes[0] !== UNCOMPRESSED_POINT_TAG) {
    throw new Error("Generated VAPID public key was not an uncompressed P-256 point");
  }
  if (Buffer.from(privateKey, "base64url").byteLength !== PRIVATE_KEY_BYTES) {
    throw new Error("Generated VAPID private key was not 32 bytes");
  }
  return { publicKey, privateKey };
}

/**
 * A file that is missing, unreadable, or holds something unusable is replaced
 * rather than treated as an error — the same call `pairing-token.ts` makes. The
 * cost is that each device re-subscribes once; a gateway that refuses to start
 * because of its key file is worse.
 */
export async function loadOrCreateVapidKeys(
  filePath: string,
  subject: string = DEFAULT_VAPID_SUBJECT,
): Promise<WebPushConfig> {
  try {
    const raw = await readFile(filePath, "utf8");
    if (raw.length <= MAX_KEY_FILE_BYTES) {
      const parsed: unknown = JSON.parse(raw);
      if (isStoredKeys(parsed)) return { publicKey: parsed.publicKey, privateKey: parsed.privateKey, subject };
    }
  } catch {
    // Absent, unreadable, or not JSON; mint below.
  }
  const keys = generateVapidKeys();
  await writeKeysAtomically(filePath, keys);
  return { ...keys, subject };
}

async function writeKeysAtomically(filePath: string, keys: StoredKeys): Promise<void> {
  const directory = path.dirname(filePath);
  await mkdir(directory, { recursive: true, mode: 0o700 });
  const temporary = path.join(directory, `.${path.basename(filePath)}.${randomBytes(6).toString("hex")}.tmp`);
  try {
    await writeFile(temporary, `${JSON.stringify(keys, null, 2)}\n`, { encoding: "utf8", mode: 0o600 });
    await rename(temporary, filePath);
  } catch (error) {
    await unlink(temporary).catch(() => {});
    throw error;
  }
}
